# ---------------------------------------------------------------------------------- 
    # Copyright (c) Microsoft Corporation. All rights reserved.
    # Licensed under the MIT License. See License in the project root for
    # license information.
# ----------------------------------------------------------------------------------

<#

.SYNOPSIS
    PowerShell script that enables you to register multiple SAP systems with Azure Center for SAP solutions in parallel.

.DESCRIPTION
    This script:
    - fetches the SAP system details required for registration from the input csv file
    - creates a job for registering each SID as a VIS resource and monitors the job status
    - provides the registration status of each SID on console as well as an output csv file

.PARAMETER InputFile
    This is the full path of the csv file which has the input data for the existing SAP systems on Azure that are to be registered as a Virtual Instance for SAP solutions resource.

.PARAMETER OutputFile
    This is the full path of the output csv file which will be generated by the script with the status of the registration process.

.PARAMETER MonitoringIntervalInSeconds
    This specifies the number of seconds for which script will wait to check the status of registration during the execution

.PARAMETER MaxParallelJobs
    This specifies the limit of parallel jobs that will run at a time. There is one job triggered per SID in the input csv file.

.EXAMPLE
    C:\MassRegistrationOfSAPSystems\RegisterSIDs.ps1 -InputFile "C:\input\RegistrationData.csv" -OutputFile "C:\output\RegistrationDataOutput.csv"

.EXAMPLE
    C:\MassRegistrationOfSAPSystems\RegisterSIDs.ps1 -InputFile "C:\input\RegistrationData.csv" -OutputFile "C:\output\RegistrationDataOutput.csv" -MonitoringIntervalInSeconds 30 -MaxParallelJobs 10

#>

# Defining the parameters required for the script
[cmdletbinding()]
    Param( 
        [parameter(mandatory = $true)]
        [String]$InputFile,
        [parameter(mandatory = $true)]
        [String]$OutputFile,
        [Parameter(Mandatory = $false)]
        [Int]$MonitoringIntervalInSeconds = 30,
        [Parameter(Mandatory = $false)]
        [Int]$MaxParallelJobs = 10
    )

# Declaring variable as array for storing job definitions
$Jobdefs = @()

function ConvertTo-TagHashtable
{
    param(
        [AllowEmptyString()]
        [String]$Tag
    )

    $Tags = @{}
    if ([string]::IsNullOrWhiteSpace($Tag))
    {
        return $Tags
    }

    foreach ($TagEntry in ($Tag -split ';'))
    {
        $TagEntry = $TagEntry.Trim()
        if ($TagEntry.Length -eq 0)
        {
            continue
        }

        $TagParts = $TagEntry -split '=', 2
        if ($TagParts.Count -ne 2)
        {
            throw "Tag entry '$TagEntry' is not valid. Use the format 'key = ""value""; key2 = ""value2""'."
        }

        $TagName = $TagParts[0].Trim()
        $TagValue = $TagParts[1].Trim()
        if ($TagName.Length -eq 0)
        {
            throw "Tag entry '$TagEntry' has an empty tag name."
        }

        $HasDoubleQuotes = $TagValue.StartsWith('"') -or $TagValue.EndsWith('"')
        $HasSingleQuotes = $TagValue.StartsWith("'") -or $TagValue.EndsWith("'")
        if ($HasDoubleQuotes)
        {
            if ($TagValue.Length -lt 2 -or -not ($TagValue.StartsWith('"') -and $TagValue.EndsWith('"')))
            {
                throw "Tag entry '$TagEntry' has mismatched double quotes."
            }

            $TagValue = $TagValue.Substring(1, $TagValue.Length - 2)
        }
        elseif ($HasSingleQuotes)
        {
            if ($TagValue.Length -lt 2 -or -not ($TagValue.StartsWith("'") -and $TagValue.EndsWith("'")))
            {
                throw "Tag entry '$TagEntry' has mismatched single quotes."
            }

            $TagValue = $TagValue.Substring(1, $TagValue.Length - 2)
        }

        if ($Tags.ContainsKey($TagName))
        {
            throw "Tag name '$TagName' is specified more than once."
        }

        $Tags[$TagName] = $TagValue
    }

    return $Tags
}

function ConvertTo-ManagedResourcesNetworkAccessType
{
    param(
        [AllowEmptyString()]
        [String]$NetworkAccessType
    )

    if ([string]::IsNullOrWhiteSpace($NetworkAccessType))
    {
        return $null
    }

    $NetworkAccessType = $NetworkAccessType.Trim()
    if ($NetworkAccessType -notin @('Private', 'Public'))
    {
        throw "Network access type '$NetworkAccessType' is not valid. It must be either 'Private' or 'Public'."
    }

    return $NetworkAccessType
}

# Importing the input file
$file = Import-CSV $InputFile

# Iterating through each line of the input file
foreach($line in $file)
{ 
    # Getting deployment specific values
    $SID = $line.SID
    $Location = $line.Location
    $Environment = $line.Environment
    $Product = $line.Product
    $CentralServerVmId = $line.CentralServerVmId
    $ResourceGroup = $CentralServerVmId.Split("/")[4]
    $MsiID = $line.MsiId
    $ManagedRgName = $line.ManagedResourceGroupName
    $ManagedRgStorageAccountName = $line.ManagedRgStorageAccountName
    $ManagedResourcesNetworkAccessType = $line.ManagedResourcesNetworkAccessType
    $Tags = ConvertTo-TagHashtable -Tag $line.Tag

    # Checking if the optional parameters are provided with valid names in the input file
    if ($ManagedRgName -match '^[a-zA-Z0-9\._\-\(\)]{1,90}$')
    {
        $ManagedRgName = $ManagedRgName.Trim()
    }
    elseif ([string]::IsNullOrEmpty($ManagedRgName) -or $ManagedRgName.Trim().Length -eq 0)
    {
        $ManagedRgName = $null
    }
    else {
        throw "Resource group name '$ManagedRgName' is not valid. It must only contain alphanumeric characters, periods, underscores, hyphens, and parentheses, and be between 1 and 90 characters in length. Please check https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftresources for more details."
    }
    
    if ($ManagedRgStorageAccountName -match '^[a-z0-9]{3,24}$')
    {
        $ManagedRgStorageAccountName = $ManagedRgStorageAccountName.Trim()
    }
    elseif ([string]::IsNullOrEmpty($ManagedRgStorageAccountName) -or $ManagedRgStorageAccountName.Trim().Length -eq 0)
    {
        $ManagedRgStorageAccountName = $null
    }
    else {
        throw "Storage account name '$ManagedRgStorageAccountName' is not valid. It must only contain lowercase alphanumeric characters and be between 3 and 24 characters in length. Please check https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftstorage for more details."
    }

    $ManagedResourcesNetworkAccessType = ConvertTo-ManagedResourcesNetworkAccessType `
        -NetworkAccessType $ManagedResourcesNetworkAccessType

    # Creating script block for parallel execution
    $ScriptBlockCopy = {
        param($ResourceGroup, $SID, $Location, $Environment, $Product, $CentralServerVmId, `
        $ManagedRgName, $MsiID, $Tags, $ManagedRgStorageAccountName, $ManagedResourcesNetworkAccessType)

        $RegistrationParameters = @{
            ResourceGroupName = $ResourceGroup
            Name = $SID
            Location = $Location
            Environment = $Environment
            SapProduct = $Product
            CentralServerVmId = $CentralServerVmId
            IdentityType = 'UserAssigned'
            UserAssignedIdentity = @{ $MsiID = @{} }
        }

        if ($Tags.Count -gt 0)
        {
            $RegistrationParameters.Tag = $Tags
        }

        if (-not [string]::IsNullOrWhiteSpace($ManagedRgName))
        {
            $RegistrationParameters.ManagedResourceGroupName = $ManagedRgName
        }

        if (-not [string]::IsNullOrWhiteSpace($ManagedRgStorageAccountName))
        {
            $RegistrationParameters.ManagedRgStorageAccountName = $ManagedRgStorageAccountName
        }

        if (-not [string]::IsNullOrWhiteSpace($ManagedResourcesNetworkAccessType))
        {
            $RegistrationParameters.ManagedResourcesNetworkAccessType = $ManagedResourcesNetworkAccessType
        }

        New-AzWorkloadsSapVirtualInstance @RegistrationParameters
    }
    
    # Generating random string for job name
    $random = -join ((65..90) + (97..122) | Get-Random -Count 8 | % {[char]$_})

    # Starting the job if the number of running jobs is less than MaxParallelJobs otherwise wait for defined time
    while ($true) {
        if ((Get-Job -State Running).Count -le $MaxParallelJobs)
        {
            Start-Job -ScriptBlock $ScriptBlockCopy -ArgumentList $ResourceGroup, $SID, $Location, `
                $Environment, $Product, $CentralServerVmId, $ManagedRgName, $MsiID, $Tags, `
                $ManagedRgStorageAccountName, $ManagedResourcesNetworkAccessType -Name $random
            break
        }
        else
        {
            Write-Host "Reached maximum parallel jobs, waiting for $MonitoringIntervalInSeconds seconds"
            Start-Sleep -Seconds $MonitoringIntervalInSeconds
        }
    }

    # Storing job definitions to monitor the status of the jobs
    $Jobdefs += New-Object PSCustomObject -Property @{JobName = $random; SID = $SID; State = "Running"}
}

Write-Host "Waiting for all jobs to complete"

# Declaring variable as array for storing completed jobs
$Completed = [System.Collections.ArrayList]::new()

while($Completed.Count -ne ($Jobdefs | Measure-Object).Count)
{
    # Waiting for monitoring interval specified before checking the status of the jobs
    Start-Sleep -Seconds $MonitoringIntervalInSeconds

    Write-Host "$($Completed.Count) Jobs completed out of $(($Jobdefs | Measure-Object).Count)"

    # Iterating through each job definition
    foreach($Jobdef in $Jobdefs)
    {

        # Checking if the job is already completed, if yes then skip the loop
        if($Completed.Contains($Jobdef.JobName))
        {
            continue
        }
        
        # Checking the status of the job
        $Job = Get-Job -Name $($Jobdef.JobName)

        # Checking if the job is not running
        if($Job.State -ne "Running")
        {
            # Getting the output of the job
            $Out = Receive-Job -Name $($Jobdef.JobName) | ConvertFrom-Json
            
            # Adding the job to completed jobs list. The job may have either succeeded or failed which can be seen from the registration status available in the output csv file.
            $null = $Completed.Add($Jobdef.JobName)
            
            # Fetching the record from the input file for the current job
            $filerec = $file | Where-Object {$_.SID -eq $Jobdef.SID}
            
            # Checking if the job succeeded or failed and update the status in record
            if($Out.properties.ProvisioningState -eq "Succeeded")
            {
                $filerec.State = "Succeeded"
            }
            else
            {
                $filerec.State = "Failed"
            }
            
            Write-Host "The registration for $($Jobdef.SID) completed with provisioning state as $($filerec.State)"
            
            # Updating the details of the job in a variable
            $Jobrec = $Jobdefs | Where-Object {$_.SID -eq $Jobdef.SID}
            
            # Updating the status of the job in same variable so that it can be used to update the status of the job in the output csv file
            $Jobrec.State = $Job.State

        }
    }
}

# Showing the status of the jobs on console
$Jobdefs | Format-Table -AutoSize

# Exporting the status of the jobs to output file
$file | Export-Csv $OutputFile -Force -NoTypeInformation